# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30d52c8343cd541fb924068f083c5f7e870d601affa799df9269bcb60091c2fba6f9703754db87b1f93dba23e62cb721c643b79ed55a968ee19a35732b7563aa

test:
  secret_key_base: 7f832b65d796bf348a42e8592f7028d0adbce5e3a0ae48d38cd67bcd42eab89b9b7ee4eaa66cd67664b043739d0d156b7c45d37bb30423b69133d2435bc61602

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
